name: fr
channels:
  - https://mirrors.ustc.edu.cn/anaconda/cloud/msys2
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - cffi=1.14.5
  - colorama=0.4.4
  - cycler=0.10.0
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - freetype=2.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - intel-openmp=2021.2.0
  - ipykernel=5.3.4
  - ipython=7.23.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=3.0.0
  - joblib=1.0.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.0.1
  - matplotlib-base=3.3.4
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - msys2-conda-epoch=20160418
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - notebook=6.4.0
  - numpy=1.20.2
  - numpy-base=1.20.2
  - olefile=0.46
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.4
  - pandoc=2.12
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pickleshare=0.7.5
  - pillow=8.2.0
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - pycparser=2.20
  - pygments=2.9.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - python=3.8.0
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtpy=1.9.0
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - send2trash=1.5.0
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.35.4
  - terminado=0.9.4
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - astroid==2.6.2
    - blurhash==1.1.4
    - boost==0.1
    - chardet==4.0.0
    - click==7.1.2
    - cmake==3.20.2
    - dlib==19.22.0
    - et-xmlfile==1.1.0
    - flask==2.0.1
    - flask-cors==3.0.10
    - flask-sqlalchemy==2.5.1
    - freetype-py==2.2.0
    - greenlet==1.1.0
    - idna==2.10
    - imutils==0.5.4
    - isort==5.9.2
    - itsdangerous==2.0.1
    - lazy-object-proxy==1.6.0
    - mastodon-py==1.5.1
    - mccabe==0.6.1
    - opencv-contrib-python==4.5.2.52
    - opencv-python==4.5.2.52
    - openpyxl==3.0.7
    - pip==21.1.3
    - pymysql==1.0.2
    - pyqt5==5.15.4
    - pyqt5-plugins==5.15.4.2.2
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.0
    - pyqt5-tools==5.15.4.3.2
    - python-dotenv==0.18.0
    - python-magic==0.4.22
    - qt5-applications==5.15.2.2.2
    - qt5-tools==5.15.2.1.2
    - requests==2.25.1
    - sqlalchemy==1.4.15
    - urllib3==1.26.4
    - werkzeug==2.0.1
    - wrapt==1.12.1
    - xlrd==2.0.1
